import { alpha, makeStyles } from '@material-ui/core'

export const useStyles = makeStyles((theme) => ({
  listItem: {
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 7,
    paddingBottom: 7,
  },
  boxWrapper: {
    minWidth: 500,
    padding: 30,
    alignItems: 'center',
    justifyContent: 'center',
    [theme.breakpoints.down('sm')]: {
      minWidth: 'auto',
    },
  },
  listWrapper: {
    padding: 0,
    marginBottom: 25,
    marginTop: 15,
  },
  emailWrapper: {
    marginTop: 0,
    [theme.breakpoints.down('sm')]: {
      marginTop: '15px',
    },
  },
  authThumb: {
    backgroundColor: alpha(theme.palette.primary.main, 0.12),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    width: '100%',
    [theme.breakpoints.up('md')]: {
      width: '50%',
      order: 2,
    },
  },
  authContent: {
    padding: 35,
    paddingTop: 50,
    width: '100%',
    '& .MuiInputBase-input,& .MuiTypography-body1, & p': {
      fontFamily: 'Poppins',
    },
    [theme.breakpoints.up('md')]: {
      width: (props) => (props.variant === 'default' ? '50%' : '100%'),
      order: 1,
    },
    [theme.breakpoints.up('xl')]: {
      padding: 50,
    },
    [theme.breakpoints.down('sm')]: {
      padding: '13px',
    },
  },
  titleRoot: {
    color: '#19519D',
    fontWeight: 600,
    fontSize: 24,
    lineHeight: '36px',
    marginBottom: 10,
    fontFamily: 'Poppins',
  },
  subTitleRoot: {
    color: '#000000',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '21px',
    marginBottom: 20,
    fontFamily: 'Poppins',
  },
  textAcc: {
    textAlign: 'right',
    paddingTop: 20,
    color: '#016AE9',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '21px',
    fontFamily: 'Poppins',
    display: 'block',
  },
  accntTxt: {
    textAlign: 'center',
    paddingTop: 20,
    color: '#000',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '21px',
    fontFamily: 'Poppins',
  },
  submitButton: {
    width: '100%',
    height: 50,
    backgroundColor: '#929292',
    color: '#fff',
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '21px',
    fontFamily: 'Poppins',
    textTransform: 'inherit',
  },
  submitButtonBlue: {
    width: '100%',
    height: 50,
    backgroundColor: '#016AE9',
    color: '#fff',
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '21px',
    fontFamily: 'Poppins',
    textTransform: 'inherit',
  },
  loginButton: {
    width: '100%',
    height: 50,
    backgroundColor: '#016AE9',
    color: '#fff',
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '21px',
    fontFamily: 'Poppins',
    textTransform: 'inherit',
  },
  resendButton: {
    width: 'auto',
    backgroundColor: '#fff !important',
    color: '#016ae9 !important',
    fontWeight: 400,
    fontSize: 14,
    margin: '0 3px',
    lineHeight: '21px',
    fontFamily: 'Poppins',
    textTransform: 'inherit',
    padding: '0 !important',
  },
  topBar: {
    position: 'fixed',
    width: '100%',
    marginTop: 0,
    marginLeft: '-50%',
    left: '50%',
    background: '#fff',
    boxShadow: '0px 4px 6px 0px #00000026',
    zIndex: 99999,
    top: 0,
    height: 71,
  },
  topLogo: {
    height: 32,
    marginLeft: 60,
    verticalAlign: 'middle',
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
  },
  regsLink: {
    width: '100%',
    height: 50,
    backgroundColor: '#016AE9',
    color: '#fff',
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '50px',
    fontFamily: 'Poppins',
    textTransform: 'inherit',
    display: 'block',
    textAlign: 'center',
    borderRadius: '5px',
    boxShadow:
      '0px 3px 1px -2px rgb(0 0 0 / 20%), 0px 2px 2px 0px rgb(0 0 0 / 14%), 0px 1px 5px 0px rgb(0 0 0 / 12%)',
  },

    labelRoot: {
        color: "#000000",
        fontWeight: 700,
        fontSize: 14,
        lineHeight: "21px",
        fontFamily: "Poppins",
    },
    textFieldRoot: {
        "& .MuiOutlinedInput-notchedOutline": {
            borderColor: alpha(theme.palette.common.dark, 0.4),
        },
        marginTop: 5,
        marginBottom: 15,
        borderColor: "#929292",
    },
    succImg: {
        maxWidth: 300,
        maxHeight: 174,
    },
    formcontrolLabelRoot: {
        "& .MuiFormControlLabel-label": {
            [theme.breakpoints.down("xs")]: {
                fontSize: 12,
            },
        },
    },
    logo: {
        width: 120,
        maxWidth: 120,
    },
}));

export const deletedAccountStyle = makeStyles((theme) => ({
    root: {
        width: "520px",
        margin: "0 auto",
        position: "relative",
        padding: "38px",
        boxShadow: "none",
        [theme.breakpoints.down("xs")]: {
            width: "100%",
            padding: "25px",
        },
    },
    imageContainer: {
        margin: "0 auto",
        height: "168px",
        width: "168px",
        background: "#F7F7F7",
        borderRadius: "100%",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
    },
    image: {
        height: "120px",
        width: "120px",
    },

    title: {
        color: "#19519D",
        fontSize: "24px",
        fontFamily: "Poppins SemiBold",
        marginTop: "44px",
        textAlign: "center",
    },
    subTitle: {
        color: theme.palette.common.black,
        fontSize: "14px",
        fontFamily: "Poppins Regular",
        marginTop: "10px",
        textAlign: "center",
    },
    description: {
        color: theme.palette.common.black,
        fontSize: "14px",
        fontFamily: "Poppins Bold",
        marginTop: "22px",
        textAlign: "center",
    },
    primaryBtn: {
        fontFamily: "Poppins SemiBold",
        backgroundColor: "#016AE9",
        fontSize: "14px",
        padding: "14px 0",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        cursor: "pointer",
        transition: "all 0.3s",
        textTransform: "none",
        marginTop: "22px",
        color: theme.palette.common.white,
        "&:hover": {
            backgroundColor: "#0246f3ed",
        },
    },
    thankyouNote: {
        color: "#535353",
        fontSize: "14px",
        fontFamily: "Poppins Bold",
        marginTop: "22px",
        textAlign: "center",
    },
}));
