export const tooltipStyles = {
  tooltip: {
    width: '138px',
    minHeight: '46px',
    background: '#FFFFFF',
    border: '1px solid #E5E5E5',
    boxSizing: 'border-box',
    boxShadow: '0px 0px 6px rgba(0, 0, 0, 0.1)',
    borderRadius: '5px',
    padding: '9px 14px',
    fontFamily: "'Poppins'",
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '9px',
    lineHeight: '14px',
    color: '#000000',
    whiteSpace: 'pre-wrap',
    zIndex: '99999 !important',
  },
}
