export const criterias = {
  gender: [
    { value: 'Female', label: 'Female', checked: true },
    { value: 'Male', label: 'Male', checked: false },
  ],
  age: [
    { value: '18 - 25', label: '18 - 25', checked: false },
    { value: '25 - 30', label: '25 - 30', checked: true },
    { value: '30 - 35', label: '30 - 35', checked: false },
    { value: '35 - 45', label: '35 - 45', checked: true },
    { value: '55+', label: '55+', checked: false },
  ],
  employmentStatus: [
    {
      value: 'full time',
      label: 'Full Time (35+ hours / week)',
      checked: true,
    },
    {
      value: 'part time',
      label: 'Part Time (1-34 hour / week)',
      checked: false,
    },
    { value: 'unemployed', label: 'Unemployed', checked: false },
  ],
  degreeObtained: [
    {
      value: 'US High School Diploma ($0.05 add)',
      label: 'US High School Diploma ($0.05 add)',
      checked: true,
    },
    {
      value: 'US Bachelor’s Degree ($0.50 add)',
      label: 'US Bachelor’s Degree ($0.50 add)',
      checked: false,
    },
    {
      value: 'US Graduate Degree ($0.65 add)',
      label: 'US Graduate Degree ($0.65 add)',
      checked: false,
    },
  ],
  borrowerStatus: [
    { value: 'Auto Loan', label: 'Auto Loan', checked: false },
    { value: 'Business Loan', label: 'Business Loan', checked: true },
    { value: 'Credit Cards', label: 'Credit Cards', checked: false },
    { value: 'Home Mortgage', label: 'Home Mortgage', checked: true },
    { value: 'Personal Loan', label: 'Personal Loan', checked: false },
    { value: 'Student Loan', label: 'Student Loan', checked: false },
  ],
  maritalStatus: [
    { value: 'Divorced', label: 'Divorced', checked: true },
    { value: 'Married', label: 'Married', checked: false },
    { value: 'Single', label: 'Single', checked: false },
  ],
  mobileDevice: [
    { value: 'Android', label: 'Android', checked: true },
    { value: 'iPhone', label: 'iPhone', checked: false },
  ],
  internetUsage: [
    { value: '1 to 4 hours', label: '1 to 4 hours', checked: true },
    { value: '5 to 7 hours', label: '5 to 7 hours', checked: false },
    { value: '7+ hours', label: '7+ hours', checked: false },
  ],
  newsSources: [
    { value: 'Online News', label: 'Online News', checked: true },
    { value: 'Podcasts', label: 'Podcasts', checked: false },
    { value: 'Print', label: 'Print', checked: false },
    { value: 'Radio', label: 'Radio', checked: false },
    { value: 'Social Media', label: 'Social Media', checked: false },
    {
      value: 'TV ( Late Night Comedy, Other )',
      label: 'TV ( Late Night Comedy, Other )',
      checked: false,
    },
    {
      value: 'TV ( Local / Cable News )',
      label: 'TV ( Local / Cable News )',
      checked: false,
    },
    { value: 'Word of Month', label: 'Word of Month', checked: false },
  ],
  politicalAffiliation: [
    { value: 'Liberal', label: 'Liberal', checked: true },
    { value: 'Conservative', label: 'Conservative', checked: false },
  ],
  languageFluency: [
    {
      value: 'Brazilian Portuguese',
      label: 'Brazilian Portuguese',
      checked: false,
    },
    { value: 'Chinese Mandarin', label: 'Chinese Mandarin', checked: true },
    { value: 'Prench', label: 'Prench', checked: false },
    { value: 'German', label: 'German', checked: true },
    { value: 'Spanish', label: 'Spanish', checked: false },
  ],
  handendess: [
    { value: 'Right', label: 'Right', checked: true },
    { value: 'Left', label: 'Left', checked: false },
  ],
  employmentIndustry: [
    {
      value: 'Banking and Financial Services',
      label: 'Banking and Financial Services',
      checked: true,
    },
    { value: 'Education', label: 'Education', checked: false },
    { value: 'Food and Beverage', label: 'Food and Beverage', checked: false },
    {
      value: 'Government and Non - Profit',
      label: 'Government and Non - Profit',
      checked: false,
    },
    { value: 'Healthcare', label: 'Healthcare', checked: false },
    { value: 'Manufacturing', label: 'Manufacturing', checked: false },
    {
      value: 'Retail, wholesale, and Distribution',
      label: 'Retail, wholesale, and Distribution',
      checked: false,
    },
    {
      value: 'Software and IT Services',
      label: 'Software and IT Services',
      checked: false,
    },
  ],
  householdIncome: [
    { value: '$100,000 or more', label: '$100,000 or more', checked: true },
    { value: '$75,000 - $99,999', label: '$75,000 - $99,999', checked: false },
    { value: '$50,000 - $74,999', label: '$50,000 - $74,999', checked: false },
    { value: '$25,000 - $44,999', label: '$25,000 - $44,999', checked: false },
    { value: 'Less man $25,000', label: 'Less man $25,000', checked: false },
  ],
  financialAssets: [
    {
      value: 'Certificate of Deposit',
      label: 'Certificate of Deposit',
      checked: false,
    },
    { value: 'Checking Account', label: 'Checking Account', checked: true },
    {
      value: 'Common Share Stocks',
      label: 'Common Share Stocks',
      checked: false,
    },
    {
      value: 'Exchange - Traded Fund',
      label: 'Exchange - Traded Fund',
      checked: true,
    },
    {
      value: 'Money Market Account',
      label: 'Money Market Account',
      checked: false,
    },
    { value: 'Mutual Funds', label: 'Mutual Funds', checked: false },
    {
      value: 'Real Estate Investment Trushs',
      label: 'Real Estate Investment Trushs',
      checked: false,
    },
    { value: 'Saving Account', label: 'Saving Account', checked: true },
    { value: 'Stock Options', label: 'Stock Options', checked: false },
    {
      value: 'US Treasury Bills/Goverment Debt',
      label: 'US Treasury Bills/Goverment Debt',
      checked: true,
    },
  ],
  vacationFrequency: [
    { value: 'Never', label: 'Never', checked: true },
    { value: 'Every Few Years', label: 'Every Few Years', checked: false },
    { value: 'Every Quarter', label: 'Every Quarter', checked: false },
    { value: 'Every Year', label: 'Every Year', checked: false },
    { value: 'Every Month', label: 'Every Month', checked: false },
  ],
  currentResidence: [
    { value: 'Owned', label: 'Owned', checked: true },
    { value: 'Rented', label: 'Rented', checked: false },
  ],
  insurancePolicyholder: [
    { value: 'Auto', label: 'Auto', checked: false },
    { value: 'Healthcare', label: 'Healthcare', checked: true },
    { value: 'Home Owners', label: 'Home Owners', checked: false },
    { value: 'Life', label: 'Life', checked: true },
    { value: 'Lenters', label: 'Lenters', checked: false },
  ],
  internetDevice: [
    { value: 'Dekstop', label: 'Dekstop', checked: true },
    { value: 'Laptop', label: 'Laptop', checked: false },
    {
      value: 'Smartphone or Tablet',
      label: 'Smartphone or Tablet',
      checked: false,
    },
  ],
  socialMedia: [
    { value: 'Blogger', label: 'Blogger', checked: false },
    { value: 'Facebook', label: 'Facebook', checked: true },
    { value: 'Google Account', label: 'Google Account', checked: false },
    { value: 'Linkedin', label: 'Linkedin', checked: true },
    { value: 'Myspace', label: 'Myspace', checked: false },
    { value: 'Pinterest', label: 'Pinterest', checked: false },
    { value: 'Reddit', label: 'Reddit', checked: false },
    { value: 'Tumblr', label: 'Tumblr', checked: true },
    { value: 'Twitter', label: 'Twitter', checked: false },
    { value: 'Youtube', label: 'Youtube', checked: true },
  ],
  onlinePurchase: [
    {
      value: 'Automotive Products',
      label: 'Automotive Products',
      checked: false,
    },
    { value: 'Baby and Kids', label: 'Baby and Kids', checked: true },
    { value: 'Books', label: 'Books', checked: false },
    { value: 'Clothing and Shoes', label: 'Clothing and Shoes', checked: true },
    {
      value: 'Electronics annd Computers',
      label: 'Electronics annd Computers',
      checked: false,
    },
    { value: 'Grocenes and Food', label: 'Grocenes and Food', checked: false },
    { value: 'Handmade Products', label: 'Handmade Products', checked: false },
    { value: 'Health and Beauty', label: 'Health and Beauty', checked: true },
    { value: 'Home and Garden', label: 'Home and Garden', checked: false },
    { value: 'Jewelry', label: 'Jewelry', checked: true },
    { value: 'Movies', label: 'Movies', checked: false },
    { value: 'Music', label: 'Music', checked: true },
    {
      value: 'Sports and Outdoor',
      label: 'Sports and Outdoor',
      checked: false,
    },
    { value: 'Equipment', label: 'Equipment', checked: false },
    { value: 'Toys', label: 'Toys', checked: true },
    { value: 'Video Game', label: 'Video Games', checked: true },
  ],
  electronicParticipation: [
    {
      value: 'Voted in 2016 Presidential Electron',
      label: 'Voted in 2016 Presidential Electron',
      checked: false,
    },
    {
      value: 'Voted in 2012 Presidential Electron',
      label: 'Voted in 2012 Presidential Electron',
      checked: true,
    },
  ],
  exerciseParticipation: [
    { value: 'Every day', label: 'Every day', checked: true },
    {
      value: 'Four Plus Times a Week',
      label: 'Four Plus Times a Week',
      checked: false,
    },
    { value: 'Once a Week', label: 'Once a Week', checked: false },
    { value: 'Not at all', label: 'Not at all', checked: false },
  ],
}
