export const criterias = {
  types: [
    { id: 1, label: 'System Qualifications' },
    { id: 2, label: 'Premium Qualifications' },
  ],
  options: [
    {
      id: 2,
      label: 'Location',
      typeID: 1,
      hasComp: true,
      valueType: 2,
      price: 0.5,
    },
    {
      id: 4,
      label: 'Age 18 - 25',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 5,
      label: 'Age 25 - 30',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 6,
      label: 'Age 30 - 35',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 7,
      label: 'Age 35 - 45',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 8,
      label: 'Age 45 - 55',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 9,
      label: 'Age 55 or older',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 10,
      label: 'Blogger',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 11,
      label: 'Borrower - Auto Loans',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 12,
      label: 'Borrower - Business Loan',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 13,
      label: 'Borrower - Credit Cards',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 14,
      label: 'Borrower - Home Mortgage',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 15,
      label: 'Borrower - Personal Loan',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 16,
      label: 'Borrower - Student Loan',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 17,
      label: 'Car Owner',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 18,
      label: 'Current Residence - Owned',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 19,
      label: 'Current Residence - Rented',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 20,
      label: 'Daily Internet Usage - 1 to 4 hours',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 21,
      label: 'Daily Internet Usage - 5 to 7 hours',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 22,
      label: 'Daily Internet Usage - 7+ hours',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 23,
      label: 'Employment Industry - Banking & Financial Services',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 24,
      label: 'Employment Industry - Education',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 25,
      label: 'Employment Industry - Food & Beverage',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 26,
      label: 'Employment Industry - Government & Non-Profit',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 27,
      label: 'Employment Industry - Healthcare',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 28,
      label: 'Employment Industry - Manufacturing',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 29,
      label: 'Employment Industry - Media & Entertainment',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 30,
      label: 'Employment Industry - Retail, Wholesale & Distribution',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 31,
      label: 'Employment Industry - Software & IT Services',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 32,
      label: 'Employment Sector - Non-Profit',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 33,
      label: 'Employment Status - Full time (35+ hours per week)',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 34,
      label: 'Employment Status - Part time (1-34 hours per week)',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 35,
      label: 'Employment Status - Unemployed',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 36,
      label: 'Exercise - Every Day',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 37,
      label: 'Exercise - Four Plus Times a Week',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 38,
      label: 'Exercise - Not at All',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 39,
      label: 'Exercise - Once a Week',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 40,
      label: 'Exercise - Two to Three Times a Week',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 41,
      label: 'Facebook Account Holder',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 42,
      label: 'Financial Asset Owned - Certificate of Deposit (CD)',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 43,
      label: 'Financial Asset Owned - Checking Account',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 44,
      label: 'Financial Asset Owned - Common Share Stocks',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 45,
      label: 'Financial Asset Owned - Exchange-Traded Fund (ETF)',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 46,
      label: 'Financial Asset Owned - Money Market Account',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 47,
      label: 'Financial Asset Owned - Mutual Funds',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 48,
      label: 'Financial Asset Owned - Real Estate Investment Trusts (REITs)',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 49,
      label: 'Financial Asset Owned - Savings Account',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 50,
      label: 'Financial Asset Owned - Stock Options',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 51,
      label: 'Financial Asset Owned - U.S. Treasury Bills/Government Debt',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 52,
      label: 'Gender - Female',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 53,
      label: 'Gender - Male',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 54,
      label: 'Google Account Holder',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 55,
      label: 'Handedness - Left',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 56,
      label: 'Handedness - Right',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 57,
      label: 'Household Income - $100,000 or more',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 58,
      label: 'Household Income - $25,000 - $49,999',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 59,
      label: 'Household Income - $50,000 - $74,999',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 60,
      label: 'Household Income - $75,000 - $99,999',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 61,
      label: 'Household Income - Less than $25,000',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 62,
      label: 'Insurance Policyholder - Auto Insurance',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 63,
      label: 'Insurance Policyholder - Healthcare Insurance',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 64,
      label: 'Insurance Policyholder - Home Owners Insurance',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 65,
      label: 'Insurance Policyholder - Life Insurance',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 66,
      label: 'Insurance Policyholder - Renters Insurance',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 67,
      label: 'Job Function - Accounting & Finance',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 68,
      label: 'Job Function - Administrative',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 69,
      label: 'Job Function - Arts & Design',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 70,
      label: 'Job Function - Education & Training',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 71,
      label: 'Job Function - Engineering',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 72,
      label: 'Job Function - Information Technology',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 73,
      label: 'Job Function - Management',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 74,
      label: 'Job Function - Marketing, Sales & Business Development',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 75,
      label: 'Job Function - Operations',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 76,
      label: 'Language Fluency (Basic) - Brazilian Portuguese',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 77,
      label: 'Language Fluency (Basic) - Chinese Mandarin',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 78,
      label: 'Language Fluency (Basic) - French',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 79,
      label: 'Language Fluency (Basic) - German',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 80,
      label: 'Language Fluency (Basic) - Spanish',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 81,
      label: 'LinkedIn Account Holder',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 82,
      label: 'Marital Status - Divorced',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 83,
      label: 'Marital Status - Married',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 84,
      label: 'Marital Status - Single',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 85,
      label: 'Military experience',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 86,
      label: 'Myspace Account Holder',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 87,
      label: 'Online Purchase - Automotive Products',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 88,
      label: 'Online Purchase - Baby & Kids',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 89,
      label: 'Online Purchase - Books',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 90,
      label: 'Online Purchase - Clothing & Shoes',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 91,
      label: 'Online Purchase - Electronics & Computers',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 92,
      label: 'Online Purchase - Groceries & Food',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 93,
      label: 'Online Purchase - Handmade Products',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 94,
      label: 'Online Purchase - Health & Beauty',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 95,
      label: 'Online Purchase - Home & Garden',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 96,
      label: 'Online Purchase - Jewelry',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 97,
      label: 'Online Purchase - Movies',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 98,
      label: 'Online Purchase - Music',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 99,
      label: 'Online Purchase - Sports & Outdoor Equipment',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 100,
      label: 'Online Purchase - Toys',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 101,
      label: 'Online Purchase - Videogames',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 102,
      label: 'Parenthood Status',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 103,
      label: 'Pinterest Account Holder',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 104,
      label: 'Primary Internet Device - Desktop',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 105,
      label: 'Primary Internet Device - Laptop',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 106,
      label: 'Primary Internet Device - Smartphone or Tablet',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 107,
      label: 'Primary Mobile Device - Android',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 108,
      label: 'Primary Mobile Device - iPhone',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 109,
      label: 'Primary News Source - Online News (News Websites, News Apps)',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 110,
      label: 'Primary News Source - Podcasts',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 111,
      label: 'Primary News Source - Print (Newspapers & Periodicals)',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 112,
      label: 'Primary News Source - Radio (AM/FM, Internet, Satellite)',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 113,
      label: 'Primary News Source - Social Media',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 114,
      label: 'Primary News Source - TV (Late Night Comedy, Other)',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 115,
      label: 'Primary News Source - TV (Local/Cable News Broadcast)',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 116,
      label: 'Primary News Source - Word of Mouth',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 117,
      label: 'Reddit Account Holder',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 118,
      label: 'Single Family Home Resident',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 119,
      label: 'Smoker',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 120,
      label: 'Tablet Owner',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 121,
      label: 'Tumblr Account Holder',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 122,
      label: 'Twitter Account Holder',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 123,
      label: "US Bachelor's Degree",
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 124,
      label: 'US Graduate Degree',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 125,
      label: 'US High School Graduate',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 126,
      label: 'US Political Affiliation - Conservative',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 127,
      label: 'US Political Affiliation - Liberal',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 128,
      label: 'Vacation Frequency - Every Few Years',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 129,
      label: 'Vacation Frequency - Every Month',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 130,
      label: 'Vacation Frequency - Every Quarter',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 131,
      label: 'Vacation Frequency - Every Year',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 132,
      label: 'Vacation Frequency - Never',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 133,
      label: 'Voted in 2012 US Presidential Election',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 134,
      label: 'Voted in 2016 US Presidential Election',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
    {
      id: 135,
      label: 'YouTube Account Holder',
      typeID: 2,
      hasComp: false,
      valueType: 4,
      price: 0.5,
    },
  ],

  comparisions: [
    { id: 1, label: 'is', value: 'EqualTo', type: 2 },
    // { id: 2, label: 'is one of', value:'In',type:2 },
    { id: 3, label: 'is not', value: 'NotEqualTo', type: 2 },
    // { id: 4, label: 'is not one of', value:'NotIn',type:2 },
  ],
  hits: [0, 50, 100, 500, 1000, 5000, 10000],
  turefalse: [
    { id: 1, label: 'True', value: 1 },
    { id: 2, label: 'False', value: 0 },
  ],
  countries: [
    // { id: 1, label: 'Å,LAND ISLANDS (AX)', value:'AX' },
    // { id: 2, label: 'AFGHANISTAN (AF)', value:'AF' },
    // { id: 3, label: 'ALBANIA (AL)', value:'AL' },
    // { id: 4, label: 'ALGERIA (DZ)', value:'DZ' },
    // { id: 5, label: 'AMERICAN SAMOA (AS)', value:'AS' },
    // { id: 6, label: 'ANDORRA (AD)', value:'AD' },
    // { id: 7, label: 'ANGOLA (AO)', value:'AO' },
    // { id: 8, label: 'ANGUILLA (AI)', value:'AI' },
    // { id: 9, label: 'ANTARCTICA (AQ)', value:'AQ' },
    // { id: 10, label: 'ANTIGUA AND BARBUDA (AG)', value:'AG' },
    // { id: 11, label: 'ARGENTINA (AR)', value:'AR' },
    // { id: 12, label: 'ARMENIA (AM)', value:'AM' },
    // { id: 13, label: 'ARUBA (AW)', value:'AW' },
    // { id: 14, label: 'AUSTRALIA (AU)', value:'AU' },
    // { id: 15, label: 'AUSTRIA (AT)', value:'AT' },
    // { id: 16, label: 'AZERBAIJAN (AZ)', value:'AZ' },
    // { id: 17, label: 'BAHAMAS (BS)', value:'BS' },
    // { id: 18, label: 'BAHRAIN (BH)', value:'BH' },
    // { id: 19, label: 'BANGLADESH (BD)', value:'BD' },
    // { id: 20, label: 'BARBADOS (BB)', value:'BB' },
    // { id: 21, label: 'BELARUS (BY)', value:'BY' },
    // { id: 22, label: 'BELGIUM (BE)', value:'BE' },
    // { id: 23, label: 'BELIZE (BZ)', value:'BZ' },
    // { id: 24, label: 'BENIN (BJ)', value:'BJ' },
    // { id: 25, label: 'BERMUDA (BM)', value:'BM' },
    // { id: 26, label: 'BHUTAN (BT)', value:'BT' },
    // { id: 27, label: 'BOLIVIA (BO)', value:'BO' },
    // { id: 28, label: 'BOSNIA AND HERZEGOVINA (BA)', value:'BA' },
    // { id: 29, label: 'BOTSWANA (BW)', value:'BW' },
    // { id: 30, label: 'BOUVET ISLAND (BV)', value:'BV' },
    // { id: 31, label: 'BRAZIL (BR)', value:'BR' },
    // { id: 32, label: 'BRITISH INDIAN OCEAN TERRITORY (IO)', value:'IO' },
    // { id: 33, label: 'BRUNEI DARUSSALAM (BN)', value:'BN' },
    // { id: 34, label: 'BULGARIA (BG)', value:'BG' },
    // { id: 35, label: 'BURKINA FASO (BF)', value:'BF' },
    // { id: 36, label: 'BURUNDI (BI)', value:'BI' },
    // { id: 37, label: 'CÔ,TE D\'IVOIRE (CI)', value:'CI' },
    // { id: 38, label: 'CAMBODIA (KH)', value:'KH' },
    // { id: 39, label: 'CAMEROON (CM)', value:'CM' },
    // { id: 40, label: 'CANADA (CA)', value:'CA' },
    // { id: 41, label: 'CAPE VERDE (CV)', value:'CV' },
    // { id: 42, label: 'CAYMAN ISLANDS (KY)', value:'KY' },
    // { id: 43, label: 'CENTRAL AFRICAN REPUBLIC (CF)', value:'CF' },
    // { id: 44, label: 'CHAD (TD)', value:'TD' },
    // { id: 45, label: 'CHILE (CL)', value:'CL' },
    // { id: 46, label: 'CHINA (CN)', value:'CN' },
    // { id: 47, label: 'CHRISTMAS ISLAND (CX)', value:'CX' },
    // { id: 48, label: 'COCOS (KEELING) ISLANDS (CC)', value:'CC' },
    // { id: 49, label: 'COLOMBIA (CO)', value:'CO' },
    // { id: 50, label: 'COMOROS (KM)', value:'KM' },
    // { id: 51, label: 'CONGO (CG)', value:'CG' },
    // { id: 52, label: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE (CD)', value:'CD' },
    // { id: 53, label: 'COOK ISLANDS (CK)', value:'CK' },
    // { id: 54, label: 'COSTA RICA (CR)', value:'CR' },
    // { id: 55, label: 'CROATIA (HR)', value:'HR' },
    // { id: 56, label: 'CUBA (CU)', value:'CU' },
    // { id: 57, label: 'CYPRUS (CY)', value:'CY' },
    // { id: 58, label: 'CZECH REPUBLIC (CZ)', value:'CZ' },
    // { id: 59, label: 'DENMARK (DK)', value:'DK' },
    // { id: 60, label: 'DJIBOUTI (DJ)', value:'DJ' },
    // { id: 61, label: 'DOMINICA (DM)', value:'DM' },
    // { id: 62, label: 'DOMINICAN REPUBLIC (DO)', value:'DO' },
    // { id: 63, label: 'ECUADOR (EC)', value:'EC' },
    // { id: 64, label: 'EGYPT (EG)', value:'EG' },
    // { id: 65, label: 'EL SALVADOR (SV)', value:'SV' },
    // { id: 66, label: 'EQUATORIAL GUINEA (GQ)', value:'GQ' },
    // { id: 67, label: 'ERITREA (ER)', value:'ER' },
    // { id: 68, label: 'ESTONIA (EE)', value:'EE' },
    // { id: 69, label: 'ETHIOPIA (ET)', value:'ET' },
    // { id: 70, label: 'FALKLAND ISLANDS (MALVINAS) (FK)', value:'FK' },
    // { id: 71, label: 'FAROE ISLANDS (FO)', value:'FO' },
    // { id: 72, label: 'FIJI (FJ)', value:'FJ' },
    // { id: 73, label: 'FINLAND (FI)', value:'FI' },
    // { id: 74, label: 'FRANCE (FR)', value:'FR' },
    // { id: 75, label: 'FRENCH GUIANA (GF)', value:'GF' },
    // { id: 76, label: 'FRENCH POLYNESIA (PF)', value:'PF' },
    // { id: 77, label: 'FRENCH SOUTHERN TERRITORIES (TF)', value:'TF' },
    // { id: 78, label: 'GABON (GA)', value:'GA' },
    // { id: 79, label: 'GAMBIA (GM)', value:'GM' },
    // { id: 80, label: 'GEORGIA (GE)', value:'GE' },
    // { id: 81, label: 'GERMANY (DE)', value:'DE' },
    // { id: 82, label: 'GHANA (GH)', value:'GH' },
    // { id: 83, label: 'GIBRALTAR (GI)', value:'GI' },
    // { id: 84, label: 'GREECE (GR)', value:'GR' },
    // { id: 85, label: 'GREENLAND (GL)', value:'GL' },
    // { id: 86, label: 'GRENADA (GD)', value:'GD' },
    // { id: 87, label: 'GUADELOUPE (GP)', value:'GP' },
    // { id: 88, label: 'GUATEMALA (GT)', value:'GT' },
    // { id: 89, label: 'GUERNSEY (GG)', value:'GG' },
    // { id: 90, label: 'GUINEA (GN)', value:'GN' },
    // { id: 91, label: 'GUINEA-BISSAU (GW)', value:'GW' },
    // { id: 92, label: 'GUYANA (GY)', value:'GY' },
    // { id: 93, label: 'HAITI (HT)', value:'HT' },
    // { id: 94, label: 'HEARD ISLAND AND MCDONALD ISLANDS (HM)', value:'HM' },
    // { id: 95, label: 'HOLY SEE (VATICAN CITY STATE) (VA)', value:'VA' },
    // { id: 96, label: 'HONDURAS (HN)', value:'HN' },
    // { id: 97, label: 'HONG KONG (HK)', value:'HK' },
    // { id: 98, label: 'HUNGARY (HU)', value:'HU' },
    // { id: 99, label: 'ICELAND (IS)', value:'IS' },
    // { id: 100, label: 'INDIA (IN)', value:'IN' },
    // { id: 101, label: 'INDONESIA (ID)', value:'ID' },
    // { id: 102, label: 'IRAN, ISLAMIC REPUBLIC OF (IR)', value:'IR' },
    // { id: 103, label: 'IRAQ (IQ)', value:'IQ' },
    // { id: 104, label: 'IRELAND (IE)', value:'IE' },
    // { id: 105, label: 'ISRAEL (IL)', value:'IL' },
    // { id: 106, label: 'ITALY (IT)', value:'IT' },
    // { id: 107, label: 'JAMAICA (JM)', value:'JM' },
    // { id: 108, label: 'JAPAN (JP)', value:'JP' },
    // { id: 109, label: 'JORDAN (JO)', value:'JO' },
    // { id: 110, label: 'KAZAKHSTAN (KZ)', value:'KZ' },
    // { id: 111, label: 'KENYA (KE)', value:'KE' },
    // { id: 112, label: 'KIRIBATI (KI)', value:'KI' },
    // { id: 113, label: 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF (KP)', value:'KP' },
    // { id: 114, label: 'KOREA, REPUBLIC OF (KR)', value:'KR' },
    // { id: 115, label: 'KUWAIT (KW)', value:'KW' },
    // { id: 116, label: 'KYRGYZSTAN (KG)', value:'KG' },
    // { id: 117, label: 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC (LA)', value:'LA' },
    // { id: 118, label: 'LATVIA (LV)', value:'LV' },
    // { id: 119, label: 'LEBANON (LB)', value:'LB' },
    // { id: 120, label: 'LESOTHO (LS)', value:'LS' },
    // { id: 121, label: 'LIBERIA (LR)', value:'LR' },
    // { id: 122, label: 'LIBYAN ARAB JAMAHIRIYA (LY)', value:'LY' },
    // { id: 123, label: 'LIECHTENSTEIN (LI)', value:'LI' },
    // { id: 124, label: 'LITHUANIA (LT)', value:'LT' },
    // { id: 125, label: 'LUXEMBOURG (LU)', value:'LU' },
    // { id: 126, label: 'MACAO (MO)', value:'MO' },
    // { id: 127, label: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF (MK)', value:'MK' },
    // { id: 128, label: 'MADAGASCAR (MG)', value:'MG' },
    // { id: 129, label: 'MALAWI (MW)', value:'MW' },
    // { id: 130, label: 'MALAYSIA (MY)', value:'MY' },
    // { id: 131, label: 'MALDIVES (MV)', value:'MV' },
    // { id: 132, label: 'MALI (ML)', value:'ML' },
    // { id: 133, label: 'MALTA (MT)', value:'MT' },
    // { id: 134, label: 'MARSHALL ISLANDS (MH)', value:'MH' },
    // { id: 135, label: 'MARTINIQUE (MQ)', value:'MQ' },
    // { id: 136, label: 'MAURITANIA (MR)', value:'MR' },
    // { id: 137, label: 'MAURITIUS (MU)', value:'MU' },
    // { id: 138, label: 'MAYOTTE (YT)', value:'YT' },
    // { id: 139, label: 'MEXICO (MX)', value:'MX' },
    // { id: 140, label: 'MICRONESIA, FEDERATED STATES OF (FM)', value:'FM' },
    // { id: 141, label: 'MOLDOVA, REPUBLIC OF (MD)', value:'MD' },
    // { id: 142, label: 'MONACO (MC)', value:'MC' },
    // { id: 143, label: 'MONGOLIA (MN)', value:'MN' },
    // { id: 144, label: 'MONTSERRAT (MS)', value:'MS' },
    // { id: 145, label: 'MOROCCO (MA)', value:'MA' },
    // { id: 146, label: 'MOZAMBIQUE (MZ)', value:'MZ' },
    // { id: 147, label: 'MYANMAR (MM)', value:'MM' },
    // { id: 148, label: 'NAMIBIA (NA)', value:'NA' },
    // { id: 149, label: 'NAURU (NR)', value:'NR' },
    // { id: 150, label: 'NEPAL (NP)', value:'NP' },
    // { id: 151, label: 'NETHERLANDS (NL)', value:'NL' },
    // { id: 152, label: 'NETHERLANDS ANTILLES (AN)', value:'AN' },
    // { id: 153, label: 'NEW CALEDONIA (NC)', value:'NC' },
    // { id: 154, label: 'NEW ZEALAND (NZ)', value:'NZ' },
    // { id: 155, label: 'NICARAGUA (NI)', value:'NI' },
    // { id: 156, label: 'NIGER (NE)', value:'NE' },
    // { id: 157, label: 'NIGERIA (NG)', value:'NG' },
    // { id: 158, label: 'NIUE (NU)', value:'NU' },
    // { id: 159, label: 'NORFOLK ISLAND (NF)', value:'NF' },
    // { id: 160, label: 'NORTHERN MARIANA ISLANDS (MP)', value:'MP' },
    // { id: 161, label: 'NORWAY (NO)', value:'NO' },
    // { id: 162, label: 'OMAN (OM)', value:'OM' },
    // { id: 163, label: 'PAKISTAN (PK)', value:'PK' },
    // { id: 164, label: 'PALAU (PW)', value:'PW' },
    // { id: 165, label: 'PALESTINIAN TERRITORY, OCCUPIED (PS)', value:'PS' },
    // { id: 166, label: 'PANAMA (PA)', value:'PA' },
    // { id: 167, label: 'PAPUA NEW GUINEA (PG)', value:'PG' },
    // { id: 168, label: 'PARAGUAY (PY)', value:'PY' },
    // { id: 169, label: 'PERU (PE)', value:'PE' },
    // { id: 170, label: 'PHILIPPINES (PH)', value:'PH' },
    // { id: 171, label: 'PITCAIRN (PN)', value:'PN' },
    // { id: 172, label: 'POLAND (PL)', value:'PL' },
    // { id: 173, label: 'PORTUGAL (PT)', value:'PT' },
    // { id: 174, label: 'PUERTO RICO (PR)', value:'PR' },
    // { id: 175, label: 'QATAR (QA)', value:'QA' },
    // { id: 176, label: 'RÉ,UNION (RE)', value:'RE' },
    // { id: 177, label: 'ROMANIA (RO)', value:'RO' },
    // { id: 178, label: 'RUSSIAN FEDERATION (RU)', value:'RU' },
    // { id: 179, label: 'RWANDA (RW)', value:'RW' },
    // { id: 180, label: 'SAINT HELENA (SH)', value:'SH' },
    // { id: 181, label: 'SAINT KITTS AND NEVIS (KN)', value:'KN' },
    // { id: 182, label: 'SAINT LUCIA (LC)', value:'LC' },
    // { id: 183, label: 'SAINT PIERRE AND MIQUELON (PM)', value:'PM' },
    // { id: 184, label: 'SAINT VINCENT AND THE GRENADINES (VC)', value:'VC' },
    // { id: 185, label: 'SAMOA (WS)', value:'WS' },
    // { id: 186, label: 'SAN MARINO (SM)', value:'SM' },
    // { id: 187, label: 'SAO TOME AND PRINCIPE (ST)', value:'ST' },
    // { id: 188, label: 'SAUDI ARABIA (SA)', value:'SA' },
    // { id: 189, label: 'SENEGAL (SN)', value:'SN' },
    // { id: 190, label: 'SERBIA AND MONTENEGRO (CS)', value:'CS' },
    // { id: 191, label: 'SEYCHELLES (SC)', value:'SC' },
    // { id: 192, label: 'SIERRA LEONE (SL)', value:'SL' },
    // { id: 193, label: 'SINGAPORE (SG)', value:'SG' },
    // { id: 194, label: 'SLOVAKIA (SK)', value:'SK' },
    // { id: 195, label: 'SLOVENIA (SI)', value:'SI' },
    // { id: 196, label: 'SOLOMON ISLANDS (SB)', value:'SB' },
    // { id: 197, label: 'SOMALIA (SO)', value:'SO' },
    // { id: 198, label: 'SOUTH AFRICA (ZA)', value:'ZA' },
    // { id: 199, label: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS (GS)', value:'GS' },
    // { id: 200, label: 'SPAIN (ES)', value:'ES' },
    // { id: 201, label: 'SRI LANKA (LK)', value:'LK' },
    // { id: 202, label: 'SUDAN (SD)', value:'SD' },
    // { id: 203, label: 'SURINAME (SR)', value:'SR' },
    // { id: 204, label: 'SVALBARD AND JAN MAYEN (SJ)', value:'SJ' },
    // { id: 205, label: 'SWAZILAND (SZ)', value:'SZ' },
    // { id: 206, label: 'SWEDEN (SE)', value:'SE' },
    // { id: 207, label: 'SWITZERLAND (CH)', value:'CH' },
    // { id: 208, label: 'SYRIAN ARAB REPUBLIC (SY)', value:'SY' },
    // { id: 209, label: 'TAIWAN, PROVINCE OF CHINA (TW)', value:'TW' },
    // { id: 210, label: 'TAJIKISTAN (TJ)', value:'TJ' },
    // { id: 211, label: 'TANZANIA, UNITED REPUBLIC OF (TZ)', value:'TZ' },
    // { id: 212, label: 'THAILAND (TH)', value:'TH' },
    // { id: 213, label: 'TIMOR-LESTE (TL)', value:'TL' },
    // { id: 214, label: 'TOGO (TG)', value:'TG' },
    // { id: 215, label: 'TOKELAU (TK)', value:'TK' },
    // { id: 216, label: 'TONGA (TO)', value:'TO' },
    // { id: 217, label: 'TRINIDAD AND TOBAGO (TT)', value:'TT' },
    // { id: 218, label: 'TUNISIA (TN)', value:'TN' },
    // { id: 219, label: 'TURKEY (TR)', value:'TR' },
    // { id: 220, label: 'TURKMENISTAN (TM)', value:'TM' },
    // { id: 221, label: 'TURKS AND CAICOS ISLANDS (TC)', value:'TC' },
    // { id: 222, label: 'TUVALU (TV)', value:'TV' },
    // { id: 223, label: 'UGANDA (UG)', value:'UG' },
    // { id: 224, label: 'UKRAINE (UA)', value:'UA' },
    // { id: 225, label: 'UNITED ARAB EMIRATES (AE)', value:'AE' },
    // { id: 226, label: 'UNITED KINGDOM (GB)', value:'GB' },
    { id: 227, label: 'UNITED STATES (US)', value: 'US' },
    // { id: 228, label: 'UNITED STATES MINOR OUTLYING ISLANDS (UM)', value:'UM' },
    { id: 229, label: 'ALABAMA (AL)', value: 'AL' },
    { id: 230, label: 'ALASKA (AK)', value: 'AK' },
    { id: 231, label: 'ARIZONA (AZ)', value: 'AZ' },
    { id: 232, label: 'ARKANSAS (AR)', value: 'AR' },
    { id: 233, label: 'CALIFORNIA (CA)', value: 'CA' },
    { id: 234, label: 'COLORADO (CO)', value: 'CO' },
    { id: 235, label: 'CONNECTICUT (CT)', value: 'CT' },
    { id: 236, label: 'DELAWARE (DE)', value: 'DE' },
    { id: 237, label: 'DISTRICT OF COLUMBIA (DC)', value: 'DC' },
    { id: 238, label: 'FLORIDA (FL)', value: 'FL' },
    { id: 239, label: 'GEORGIA (GA)', value: 'GA' },
    { id: 240, label: 'HAWAII (HI)', value: 'HI' },
    { id: 241, label: 'IDAHO (ID)', value: 'ID' },
    { id: 242, label: 'ILLINOIS (IL)', value: 'IL' },
    { id: 243, label: 'INDIANA (IN)', value: 'IN' },
    { id: 244, label: 'IOWA (IA)', value: 'IA' },
    { id: 245, label: 'KANSAS (KS)', value: 'KS' },
    { id: 246, label: 'KENTUCKY (KY)', value: 'KY' },
    { id: 247, label: 'LOUISIANA (LA)', value: 'LA' },
    { id: 248, label: 'MAINE (ME)', value: 'ME' },
    { id: 249, label: 'MARYLAND (MD)', value: 'MD' },
    { id: 250, label: 'MASSACHUSETTS (MA)', value: 'MA' },
    { id: 251, label: 'MICHIGAN (MI)', value: 'MI' },
    { id: 252, label: 'MINNESOTA (MN)', value: 'MN' },
    { id: 253, label: 'MISSISSIPPI (MS)', value: 'MS' },
    { id: 254, label: 'MISSOURI (MO)', value: 'MO' },
    { id: 255, label: 'MONTANA (MT)', value: 'MT' },
    { id: 256, label: 'NEBRASKA (NE)', value: 'NE' },
    { id: 257, label: 'NEVADA (NV)', value: 'NV' },
    { id: 258, label: 'NEW HAMPSHIRE (NH)', value: 'NH' },
    { id: 259, label: 'NEW JERSEY (NJ)', value: 'NJ' },
    { id: 260, label: 'NEW MEXICO (NM)', value: 'NM' },
    { id: 261, label: 'NEW YORK (NY)', value: 'NY' },
    { id: 262, label: 'NORTH CAROLINA (NC)', value: 'NC' },
    { id: 263, label: 'NORTH DAKOTA (ND)', value: 'ND' },
    { id: 264, label: 'OHIO (OH)', value: 'OH' },
    { id: 265, label: 'OKLAHOMA (OK)', value: 'OK' },
    { id: 266, label: 'OREGON (OR)', value: 'OR' },
    { id: 267, label: 'PENNSYLVANIA (PA)', value: 'PA' },
    { id: 268, label: 'RHODE ISLAND (RI)', value: 'RI' },
    { id: 269, label: 'SOUTH CAROLINA (SC)', value: 'SC' },
    { id: 270, label: 'SOUTH DAKOTA (SD)', value: 'SD' },
    { id: 271, label: 'TENNESSEE (TN)', value: 'TN' },
    { id: 272, label: 'TEXAS (TX)', value: 'TX' },
    { id: 273, label: 'UTAH (UT)', value: 'UT' },
    { id: 274, label: 'VERMONT (VT)', value: 'VT' },
    { id: 275, label: 'VIRGINIA (VA)', value: 'VA' },
    { id: 276, label: 'WASHINGTON (WA)', value: 'WA' },
    { id: 277, label: 'WEST VIRGINIA (WV)', value: 'WV' },
    { id: 278, label: 'WISCONSIN (WI)', value: 'WI' },
    { id: 279, label: 'WYOMING (WY)', value: 'WY' },
    // { id: 280, label: 'URUGUAY (UY)', value:'UY' },
    // { id: 281, label: 'UZBEKISTAN (UZ)', value:'UZ' },
    // { id: 282, label: 'VANUATU (VU)', value:'VU' },
    // { id: 283, label: 'VENEZUELA (VE)', value:'VE' },
    // { id: 284, label: 'VIET NAM (VN)', value:'VN' },
    // { id: 285, label: 'VIRGIN ISLANDS, BRITISH (VG)', value:'VG' },
    // { id: 286, label: 'VIRGIN ISLANDS, U.S. (VI)', value:'VI' },
    // { id: 287, label: 'WALLIS AND FUTUNA (WF)', value:'WF' },
    // { id: 288, label: 'WESTERN SAHARA (EH)', value:'EH' },
    // { id: 289, label: 'YEMEN (YE)', value:'YE' },
    // { id: 290, label: 'ZAMBIA (ZM)', value:'ZM' },
    // { id: 291, label: 'ZIMBABWE (ZW)', value:'ZW' },
  ],
}
